// ══════════════════════════════════════════════════════════
// Legacy – World Cities Database (for autocomplete)
// ~250 major cities across all continents.
// ══════════════════════════════════════════════════════════

export interface City {
  name: string;
  region: string;
  country: string;
  countryCode: string;
  label: string; // "City, Region, Country"
}

const RAW: [string, string, string, string][] = [
  // North America
  ["New York", "NY", "USA", "USA"],
  ["Los Angeles", "CA", "USA", "USA"],
  ["Chicago", "IL", "USA", "USA"],
  ["Houston", "TX", "USA", "USA"],
  ["Dallas", "TX", "USA", "USA"],
  ["Phoenix", "AZ", "USA", "USA"],
  ["Philadelphia", "PA", "USA", "USA"],
  ["San Antonio", "TX", "USA", "USA"],
  ["San Diego", "CA", "USA", "USA"],
  ["San Francisco", "CA", "USA", "USA"],
  ["Austin", "TX", "USA", "USA"],
  ["Seattle", "WA", "USA", "USA"],
  ["Denver", "CO", "USA", "USA"],
  ["Washington", "DC", "USA", "USA"],
  ["Boston", "MA", "USA", "USA"],
  ["Nashville", "TN", "USA", "USA"],
  ["Portland", "OR", "USA", "USA"],
  ["Las Vegas", "NV", "USA", "USA"],
  ["Atlanta", "GA", "USA", "USA"],
  ["Miami", "FL", "USA", "USA"],
  ["Minneapolis", "MN", "USA", "USA"],
  ["Detroit", "MI", "USA", "USA"],
  ["Charlotte", "NC", "USA", "USA"],
  ["Salt Lake City", "UT", "USA", "USA"],
  ["Honolulu", "HI", "USA", "USA"],
  ["Toronto", "ON", "Canada", "CAN"],
  ["Vancouver", "BC", "Canada", "CAN"],
  ["Montreal", "QC", "Canada", "CAN"],
  ["Calgary", "AB", "Canada", "CAN"],
  ["Ottawa", "ON", "Canada", "CAN"],
  ["Mexico City", "", "Mexico", "MEX"],
  ["Guadalajara", "", "Mexico", "MEX"],
  ["Monterrey", "", "Mexico", "MEX"],
  // Europe
  ["London", "", "United Kingdom", "GBR"],
  ["Manchester", "", "United Kingdom", "GBR"],
  ["Edinburgh", "", "United Kingdom", "GBR"],
  ["Birmingham", "", "United Kingdom", "GBR"],
  ["Glasgow", "", "United Kingdom", "GBR"],
  ["Liverpool", "", "United Kingdom", "GBR"],
  ["Bristol", "", "United Kingdom", "GBR"],
  ["Leeds", "", "United Kingdom", "GBR"],
  ["Oxford", "", "United Kingdom", "GBR"],
  ["Cambridge", "", "United Kingdom", "GBR"],
  ["Bath", "", "United Kingdom", "GBR"],
  ["Paris", "", "France", "FRA"],
  ["Lyon", "", "France", "FRA"],
  ["Marseille", "", "France", "FRA"],
  ["Nice", "", "France", "FRA"],
  ["Toulouse", "", "France", "FRA"],
  ["Berlin", "", "Germany", "DEU"],
  ["Munich", "", "Germany", "DEU"],
  ["Hamburg", "", "Germany", "DEU"],
  ["Frankfurt", "", "Germany", "DEU"],
  ["Cologne", "", "Germany", "DEU"],
  ["Stuttgart", "", "Germany", "DEU"],
  ["Madrid", "", "Spain", "ESP"],
  ["Barcelona", "", "Spain", "ESP"],
  ["Valencia", "", "Spain", "ESP"],
  ["Seville", "", "Spain", "ESP"],
  ["Rome", "", "Italy", "ITA"],
  ["Milan", "", "Italy", "ITA"],
  ["Florence", "", "Italy", "ITA"],
  ["Naples", "", "Italy", "ITA"],
  ["Venice", "", "Italy", "ITA"],
  ["Amsterdam", "", "Netherlands", "NLD"],
  ["Rotterdam", "", "Netherlands", "NLD"],
  ["Brussels", "", "Belgium", "BEL"],
  ["Zurich", "", "Switzerland", "CHE"],
  ["Geneva", "", "Switzerland", "CHE"],
  ["Vienna", "", "Austria", "AUT"],
  ["Prague", "", "Czech Republic", "CZE"],
  ["Warsaw", "", "Poland", "POL"],
  ["Krakow", "", "Poland", "POL"],
  ["Budapest", "", "Hungary", "HUN"],
  ["Lisbon", "", "Portugal", "PRT"],
  ["Porto", "", "Portugal", "PRT"],
  ["Dublin", "", "Ireland", "IRL"],
  ["Copenhagen", "", "Denmark", "DNK"],
  ["Stockholm", "", "Sweden", "SWE"],
  ["Oslo", "", "Norway", "NOR"],
  ["Helsinki", "", "Finland", "FIN"],
  ["Athens", "", "Greece", "GRC"],
  ["Bucharest", "", "Romania", "ROU"],
  ["Istanbul", "", "Turkey", "TUR"],
  ["Ankara", "", "Turkey", "TUR"],
  // Asia
  ["Tokyo", "", "Japan", "JPN"],
  ["Osaka", "", "Japan", "JPN"],
  ["Kyoto", "", "Japan", "JPN"],
  ["Seoul", "", "South Korea", "KOR"],
  ["Busan", "", "South Korea", "KOR"],
  ["Beijing", "", "China", "CHN"],
  ["Shanghai", "", "China", "CHN"],
  ["Shenzhen", "", "China", "CHN"],
  ["Guangzhou", "", "China", "CHN"],
  ["Hong Kong", "", "China", "HKG"],
  ["Taipei", "", "Taiwan", "TWN"],
  ["Singapore", "", "Singapore", "SGP"],
  ["Bangkok", "", "Thailand", "THA"],
  ["Chiang Mai", "", "Thailand", "THA"],
  ["Kuala Lumpur", "", "Malaysia", "MYS"],
  ["Jakarta", "", "Indonesia", "IDN"],
  ["Bali", "", "Indonesia", "IDN"],
  ["Manila", "", "Philippines", "PHL"],
  ["Ho Chi Minh City", "", "Vietnam", "VNM"],
  ["Hanoi", "", "Vietnam", "VNM"],
  ["Mumbai", "Maharashtra", "India", "IND"],
  ["Delhi", "NCR", "India", "IND"],
  ["New Delhi", "NCR", "India", "IND"],
  ["Bangalore", "Karnataka", "India", "IND"],
  ["Chennai", "Tamil Nadu", "India", "IND"],
  ["Kolkata", "West Bengal", "India", "IND"],
  ["Hyderabad", "Telangana", "India", "IND"],
  ["Pune", "Maharashtra", "India", "IND"],
  ["Ahmedabad", "Gujarat", "India", "IND"],
  ["Surat", "Gujarat", "India", "IND"],
  ["Jaipur", "Rajasthan", "India", "IND"],
  ["Lucknow", "Uttar Pradesh", "India", "IND"],
  ["Kanpur", "Uttar Pradesh", "India", "IND"],
  ["Nagpur", "Maharashtra", "India", "IND"],
  ["Indore", "Madhya Pradesh", "India", "IND"],
  ["Bhopal", "Madhya Pradesh", "India", "IND"],
  ["Patna", "Bihar", "India", "IND"],
  ["Vadodara", "Gujarat", "India", "IND"],
  ["Coimbatore", "Tamil Nadu", "India", "IND"],
  ["Kochi", "Kerala", "India", "IND"],
  ["Thiruvananthapuram", "Kerala", "India", "IND"],
  ["Visakhapatnam", "Andhra Pradesh", "India", "IND"],
  ["Chandigarh", "Punjab/Haryana", "India", "IND"],
  ["Amritsar", "Punjab", "India", "IND"],
  ["Ludhiana", "Punjab", "India", "IND"],
  ["Jalandhar", "Punjab", "India", "IND"],
  ["Patiala", "Punjab", "India", "IND"],
  ["Dehradun", "Uttarakhand", "India", "IND"],
  ["Shimla", "Himachal Pradesh", "India", "IND"],
  ["Srinagar", "J&K", "India", "IND"],
  ["Jammu", "J&K", "India", "IND"],
  ["Varanasi", "Uttar Pradesh", "India", "IND"],
  ["Agra", "Uttar Pradesh", "India", "IND"],
  ["Allahabad", "Uttar Pradesh", "India", "IND"],
  ["Noida", "Uttar Pradesh", "India", "IND"],
  ["Gurgaon", "Haryana", "India", "IND"],
  ["Faridabad", "Haryana", "India", "IND"],
  ["Ranchi", "Jharkhand", "India", "IND"],
  ["Guwahati", "Assam", "India", "IND"],
  ["Bhubaneswar", "Odisha", "India", "IND"],
  ["Mysore", "Karnataka", "India", "IND"],
  ["Mangalore", "Karnataka", "India", "IND"],
  ["Udaipur", "Rajasthan", "India", "IND"],
  ["Jodhpur", "Rajasthan", "India", "IND"],
  ["Goa", "Goa", "India", "IND"],
  ["Rishikesh", "Uttarakhand", "India", "IND"],
  ["Islamabad", "", "Pakistan", "PAK"],
  ["Lahore", "Punjab", "Pakistan", "PAK"],
  ["Karachi", "Sindh", "Pakistan", "PAK"],
  ["Rawalpindi", "Punjab", "Pakistan", "PAK"],
  ["Faisalabad", "Punjab", "Pakistan", "PAK"],
  ["Dhaka", "", "Bangladesh", "BGD"],
  ["Colombo", "", "Sri Lanka", "LKA"],
  ["Kathmandu", "", "Nepal", "NPL"],
  // Middle East
  ["Dubai", "", "UAE", "ARE"],
  ["Abu Dhabi", "", "UAE", "ARE"],
  ["Riyadh", "", "Saudi Arabia", "SAU"],
  ["Jeddah", "", "Saudi Arabia", "SAU"],
  ["Doha", "", "Qatar", "QAT"],
  ["Tel Aviv", "", "Israel", "ISR"],
  ["Jerusalem", "", "Israel", "ISR"],
  ["Amman", "", "Jordan", "JOR"],
  ["Beirut", "", "Lebanon", "LBN"],
  ["Kuwait City", "", "Kuwait", "KWT"],
  // Africa
  ["Cairo", "", "Egypt", "EGY"],
  ["Alexandria", "", "Egypt", "EGY"],
  ["Lagos", "", "Nigeria", "NGA"],
  ["Abuja", "", "Nigeria", "NGA"],
  ["Nairobi", "", "Kenya", "KEN"],
  ["Johannesburg", "", "South Africa", "ZAF"],
  ["Cape Town", "", "South Africa", "ZAF"],
  ["Durban", "", "South Africa", "ZAF"],
  ["Accra", "", "Ghana", "GHA"],
  ["Addis Ababa", "", "Ethiopia", "ETH"],
  ["Casablanca", "", "Morocco", "MAR"],
  ["Marrakech", "", "Morocco", "MAR"],
  ["Tunis", "", "Tunisia", "TUN"],
  ["Dar es Salaam", "", "Tanzania", "TZA"],
  ["Kampala", "", "Uganda", "UGA"],
  ["Kigali", "", "Rwanda", "RWA"],
  ["Dakar", "", "Senegal", "SEN"],
  // Oceania
  ["Sydney", "NSW", "Australia", "AUS"],
  ["Melbourne", "VIC", "Australia", "AUS"],
  ["Brisbane", "QLD", "Australia", "AUS"],
  ["Perth", "WA", "Australia", "AUS"],
  ["Adelaide", "SA", "Australia", "AUS"],
  ["Auckland", "", "New Zealand", "NZL"],
  ["Wellington", "", "New Zealand", "NZL"],
  // South America
  ["São Paulo", "", "Brazil", "BRA"],
  ["Rio de Janeiro", "", "Brazil", "BRA"],
  ["Brasília", "", "Brazil", "BRA"],
  ["Buenos Aires", "", "Argentina", "ARG"],
  ["Mendoza", "", "Argentina", "ARG"],
  ["Santiago", "", "Chile", "CHL"],
  ["Lima", "", "Peru", "PER"],
  ["Bogotá", "", "Colombia", "COL"],
  ["Medellín", "", "Colombia", "COL"],
  ["Quito", "", "Ecuador", "ECU"],
  ["Montevideo", "", "Uruguay", "URY"],
  ["Caracas", "", "Venezuela", "VEN"],
  // Central America & Caribbean
  ["San José", "", "Costa Rica", "CRI"],
  ["Panama City", "", "Panama", "PAN"],
  ["Havana", "", "Cuba", "CUB"],
  ["Kingston", "", "Jamaica", "JAM"],
  ["San Juan", "PR", "USA", "USA"],
  // More US cities
  ["New Orleans", "LA", "USA", "USA"],
  ["Raleigh", "NC", "USA", "USA"],
  ["Columbus", "OH", "USA", "USA"],
  ["Indianapolis", "IN", "USA", "USA"],
  ["San Jose", "CA", "USA", "USA"],
  ["Jacksonville", "FL", "USA", "USA"],
  ["Tampa", "FL", "USA", "USA"],
  ["Orlando", "FL", "USA", "USA"],
  ["Pittsburgh", "PA", "USA", "USA"],
  ["Cincinnati", "OH", "USA", "USA"],
  ["Kansas City", "MO", "USA", "USA"],
  ["St. Louis", "MO", "USA", "USA"],
  ["Milwaukee", "WI", "USA", "USA"],
  ["Sacramento", "CA", "USA", "USA"],
  ["Tucson", "AZ", "USA", "USA"],
  ["Memphis", "TN", "USA", "USA"],
  ["Baltimore", "MD", "USA", "USA"],
  ["Boise", "ID", "USA", "USA"],
  ["Anchorage", "AK", "USA", "USA"],
  // More Europe
  ["Reykjavik", "", "Iceland", "ISL"],
  ["Tallinn", "", "Estonia", "EST"],
  ["Riga", "", "Latvia", "LVA"],
  ["Vilnius", "", "Lithuania", "LTU"],
  ["Ljubljana", "", "Slovenia", "SVN"],
  ["Zagreb", "", "Croatia", "HRV"],
  ["Belgrade", "", "Serbia", "SRB"],
  ["Sofia", "", "Bulgaria", "BGR"],
  ["Bratislava", "", "Slovakia", "SVK"],
  ["Tbilisi", "", "Georgia", "GEO"],
  ["Yerevan", "", "Armenia", "ARM"],
  ["Baku", "", "Azerbaijan", "AZE"],
  ["Kyiv", "", "Ukraine", "UKR"],
  ["Moscow", "", "Russia", "RUS"],
  ["St. Petersburg", "", "Russia", "RUS"],
  // More Asia
  ["Nagoya", "", "Japan", "JPN"],
  ["Yokohama", "", "Japan", "JPN"],
  ["Fukuoka", "", "Japan", "JPN"],
  ["Hangzhou", "", "China", "CHN"],
  ["Chengdu", "", "China", "CHN"],
  ["Wuhan", "", "China", "CHN"],
  ["Nanjing", "", "China", "CHN"],
  ["Suzhou", "", "China", "CHN"],
  ["Phnom Penh", "", "Cambodia", "KHM"],
  ["Vientiane", "", "Laos", "LAO"],
  ["Yangon", "", "Myanmar", "MMR"],
  ["Ulaanbaatar", "", "Mongolia", "MNG"],
  // More Africa
  ["Lusaka", "", "Zambia", "ZMB"],
  ["Harare", "", "Zimbabwe", "ZWE"],
  ["Maputo", "", "Mozambique", "MOZ"],
  ["Windhoek", "", "Namibia", "NAM"],
  ["Luanda", "", "Angola", "AGO"],
  ["Kinshasa", "", "DR Congo", "COD"],
  ["Algiers", "", "Algeria", "DZA"],
  ["Tripoli", "", "Libya", "LBY"],
  // More Middle East
  ["Muscat", "", "Oman", "OMN"],
  ["Manama", "", "Bahrain", "BHR"],
  ["Baghdad", "", "Iraq", "IRQ"],
  ["Tehran", "", "Iran", "IRN"],
  // More South America
  ["Asunción", "", "Paraguay", "PRY"],
  ["La Paz", "", "Bolivia", "BOL"],
  ["Georgetown", "", "Guyana", "GUY"],
  ["Cartagena", "", "Colombia", "COL"],
  ["Cali", "", "Colombia", "COL"],
  ["Cusco", "", "Peru", "PER"],
  ["Valparaíso", "", "Chile", "CHL"],
  ["Córdoba", "", "Argentina", "ARG"],
  ["Salvador", "", "Brazil", "BRA"],
  ["Fortaleza", "", "Brazil", "BRA"],
  ["Curitiba", "", "Brazil", "BRA"],
  ["Recife", "", "Brazil", "BRA"],
  // More Canada
  ["Edmonton", "AB", "Canada", "CAN"],
  ["Winnipeg", "MB", "Canada", "CAN"],
  ["Quebec City", "QC", "Canada", "CAN"],
  ["Halifax", "NS", "Canada", "CAN"],
  ["Victoria", "BC", "Canada", "CAN"],
];

export const WORLD_CITIES: City[] = RAW.map(([name, region, country, countryCode]) => ({
  name,
  region,
  country,
  countryCode,
  label: region
    ? `${name}, ${region}, ${country}`
    : `${name}, ${country}`,
}));

/**
 * Search cities by query string. Returns top 8 matches.
 * Matches on city name, region, or country.
 */
export function searchCities(query: string): City[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return WORLD_CITIES.filter(
    (c) =>
      c.name.toLowerCase().includes(q) ||
      c.region.toLowerCase().includes(q) ||
      c.country.toLowerCase().includes(q) ||
      c.label.toLowerCase().includes(q)
  ).slice(0, 8);
}
