// ══════════════════════════════════════════════════════════
// Legacy – Rich Mock Data for Demo / Development
// ══════════════════════════════════════════════════════════

import type { Profile, Relationship, UserCondition } from "./types";
export { ALL_CONDITIONS as MOCK_CONDITIONS } from "./conditions-data";

const CREATED_AT = "2024-01-01T00:00:00Z";

const portrait = (group: "men" | "women", index: number) =>
  `https://randomuser.me/api/portraits/${group}/${index}.jpg`;

const gallery = (...seeds: string[]) =>
  seeds.map((seed) => `https://picsum.photos/seed/${seed}/900/700`);

// ── Family Members ──────────────────────────────
export const MOCK_PROFILES: Profile[] = [
  {
    id: "viewer-001",
    first_name: "Alexander",
    last_name: "Montague",
    display_name: "Alex",
    gender: "male",
    avatar_url: portrait("men", 18),
    date_of_birth: "1992-03-15",
    place_of_birth: "London, United Kingdom",
    profession: "Principal Architect",
    location_city: "New York, NY, USA",
    secondary_location_city: "London, United Kingdom",
    address: "184 Kent Avenue, Brooklyn, NY 11249, USA",
    location_lat: 40.7128,
    location_lng: -74.006,
    pets: ["Luna", "Otis"],
    social_links: {
      instagram: "alex.montague",
      linkedin: "alexandermontague",
      phone_number: "+1-212-555-0142",
    },
    about_me:
      "Third-generation architect leading climate-resilient housing projects in Brooklyn. I keep the family archive organized, host Sunday dinner whenever I am home, and over-plan every trip.",
    country_code: "USA",
    gallery_photos: gallery("alex-studio", "alex-family-trip", "alex-luna"),
    role: "ADMIN",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "parent-001",
    first_name: "Edward",
    last_name: "Montague",
    display_name: "Ed",
    gender: "male",
    avatar_url: portrait("men", 62),
    date_of_birth: "1960-07-22",
    place_of_birth: "Manchester, United Kingdom",
    profession: "Cardiothoracic Surgeon",
    location_city: "London, United Kingdom",
    secondary_location_city: "Bath, United Kingdom",
    address: "24 Chester Square, London SW1W 9EA, United Kingdom",
    location_lat: 51.5074,
    location_lng: -0.1278,
    pets: [],
    social_links: {
      linkedin: "dredwardmontague",
      phone_number: "+44-20-5550-1183",
    },
    about_me:
      "Consultant surgeon at St. Thomas' Hospital. I still do the carving at Christmas, keep everyone's documents in labeled folders, and believe tea solves at least half of life's problems.",
    country_code: "GBR",
    gallery_photos: gallery("edward-conference", "edward-garden"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "parent-002",
    first_name: "Catherine",
    last_name: "Montague",
    display_name: "Cate",
    gender: "female",
    avatar_url: portrait("women", 62),
    date_of_birth: "1963-11-08",
    place_of_birth: "Edinburgh, United Kingdom",
    profession: "Professor of Literature",
    location_city: "London, United Kingdom",
    secondary_location_city: "Edinburgh, United Kingdom",
    address: "24 Chester Square, London SW1W 9EA, United Kingdom",
    location_lat: 51.5074,
    location_lng: -0.1278,
    pets: ["Milo"],
    social_links: {
      facebook: "catherine.montague",
      phone_number: "+44-20-5550-1184",
    },
    about_me:
      "Professor of Romantic literature at King's College London. I run the family book club, insist everyone sends thank-you notes, and quietly win every trivia night.",
    country_code: "GBR",
    gallery_photos: gallery("catherine-lecture", "catherine-garden", "catherine-milo"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "sibling-001",
    first_name: "Isabella",
    last_name: "Montague",
    display_name: "Izzy",
    gender: "female",
    avatar_url: portrait("women", 18),
    date_of_birth: "1995-06-12",
    place_of_birth: "London, United Kingdom",
    profession: "Foreign Correspondent",
    location_city: "Paris, France",
    secondary_location_city: "London, United Kingdom",
    address: "18 Rue de Charonne, 75011 Paris, France",
    location_lat: 48.8566,
    location_lng: 2.3522,
    pets: ["Nori", "Peach"],
    social_links: {
      instagram: "isabellamontague",
      linkedin: "isabella-montague",
    },
    about_me:
      "Paris-based journalist covering European politics and culture. I send too many voice notes, own too many coats, and usually know the best café within ten minutes of landing anywhere.",
    country_code: "FRA",
    gallery_photos: gallery("izzy-paris", "izzy-notebook", "izzy-pets"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "spouse-001",
    first_name: "Emily",
    last_name: "Carter",
    display_name: null,
    gender: "female",
    avatar_url: portrait("women", 22),
    date_of_birth: "1993-09-04",
    place_of_birth: "San Jose, CA, USA",
    profession: "Product Design Director",
    location_city: "New York, NY, USA",
    secondary_location_city: "San Francisco, CA, USA",
    address: "184 Kent Avenue, Brooklyn, NY 11249, USA",
    location_lat: 40.7128,
    location_lng: -74.006,
    pets: ["Luna", "Otis"],
    social_links: {
      instagram: "emily.carter.design",
      linkedin: "emily-carter-design",
    },
    about_me:
      "Product design leader focused on health-tech experiences. I married into the Montagues and immediately inherited holiday hosting logistics, recipe debates, and three group chats.",
    country_code: "USA",
    gallery_photos: gallery("emily-ux", "emily-nyc"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "child-001",
    first_name: "Leo",
    last_name: "Montague",
    display_name: null,
    gender: "male",
    avatar_url: portrait("men", 8),
    date_of_birth: "2021-05-18",
    place_of_birth: "New York, NY, USA",
    profession: "Preschool Explorer",
    location_city: "New York, NY, USA",
    address: "184 Kent Avenue, Brooklyn, NY 11249, USA",
    location_lat: 40.7128,
    location_lng: -74.006,
    pets: ["Luna"],
    social_links: {},
    about_me:
      "Currently specializing in dinosaur facts, blueberry waffles, and waking everyone up before sunrise on Saturdays.",
    country_code: "USA",
    gallery_photos: gallery("leo-zoo", "leo-park"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "child-002",
    first_name: "Emma",
    last_name: "Montague",
    display_name: "Em",
    gender: "female",
    avatar_url: portrait("women", 8),
    date_of_birth: "2024-01-09",
    place_of_birth: "New York, NY, USA",
    profession: "Baby",
    location_city: "New York, NY, USA",
    address: "184 Kent Avenue, Brooklyn, NY 11249, USA",
    location_lat: 40.7128,
    location_lng: -74.006,
    pets: [],
    social_links: {},
    about_me:
      "Newest branch of the family tree. Expert-level giggler, highly opinionated about nap schedules, and already the center of the photo library.",
    country_code: "USA",
    gallery_photos: gallery("emma-blanket", "emma-birthday"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "grandparent-001",
    first_name: "William",
    last_name: "Montague",
    display_name: "Will",
    gender: "male",
    avatar_url: portrait("men", 83),
    date_of_birth: "1932-02-14",
    date_of_death: "2021-10-03",
    place_of_birth: "Bath, United Kingdom",
    profession: "Barrister (Retired)",
    location_city: "Bath, United Kingdom",
    address: "7 Royal Crescent, Bath BA1 2LR, United Kingdom",
    location_lat: 51.3811,
    location_lng: -2.359,
    pets: [],
    social_links: {},
    about_me:
      "Retired King's Counsel with a perfectly maintained study and a legendary memory for birthdays. His stories still anchor the family, even after his passing.",
    country_code: "GBR",
    gallery_photos: gallery("william-study", "william-bath"),
    role: "MEMBER",
    is_alive: false,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "grandparent-002",
    first_name: "Eleanor",
    last_name: "Montague",
    display_name: "Ellie",
    gender: "female",
    avatar_url: portrait("women", 83),
    date_of_birth: "1935-09-30",
    place_of_birth: "Oxford, United Kingdom",
    profession: "Concert Pianist",
    location_city: "Bath, United Kingdom",
    address: "7 Royal Crescent, Bath BA1 2LR, United Kingdom",
    location_lat: 51.3811,
    location_lng: -2.359,
    pets: ["Poppy"],
    social_links: {},
    about_me:
      "Former concert pianist who still practices every morning at nine sharp. I taught half the grandchildren to read music and the other half to fake confidence at recitals.",
    country_code: "GBR",
    gallery_photos: gallery("eleanor-piano", "eleanor-garden", "eleanor-poppy"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "uncle-001",
    first_name: "James",
    last_name: "Montague",
    display_name: "Jim",
    gender: "male",
    avatar_url: portrait("men", 58),
    date_of_birth: "1958-04-18",
    place_of_birth: "Manchester, United Kingdom",
    profession: "Civil Engineer",
    location_city: "Sydney, NSW, Australia",
    secondary_location_city: "London, United Kingdom",
    address: "12 Hickson Road, Dawes Point NSW 2000, Australia",
    location_lat: -33.8688,
    location_lng: 151.2093,
    pets: ["Ripley"],
    social_links: {
      linkedin: "james-montague-eng",
    },
    about_me:
      "Chief engineer overseeing coastal resilience projects in Sydney. I moved in the nineties, stayed for the surf, and still call London at wildly inconvenient hours.",
    country_code: "AUS",
    gallery_photos: gallery("james-harbour", "james-surf"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "spouse-003",
    first_name: "Susan",
    last_name: "Bennett",
    display_name: null,
    gender: "female",
    avatar_url: portrait("women", 58),
    date_of_birth: "1961-08-09",
    place_of_birth: "Cleveland, OH, USA",
    profession: "Pediatrician",
    location_city: "Sydney, NSW, Australia",
    address: "12 Hickson Road, Dawes Point NSW 2000, Australia",
    location_lat: -33.8688,
    location_lng: 151.2093,
    pets: ["Ripley"],
    social_links: {
      facebook: "susan.bennett.montague",
    },
    about_me:
      "Pediatrician, gardener, and the calmest person in every room. I married into the family decades ago and somehow still end up organizing every holiday menu and every birthday call.",
    country_code: "AUS",
    gallery_photos: gallery("susan-clinic", "susan-garden"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "cousin-001",
    first_name: "Oliver",
    last_name: "Montague",
    display_name: "Ollie",
    gender: "male",
    avatar_url: portrait("men", 28),
    date_of_birth: "1990-12-01",
    place_of_birth: "Sydney, Australia",
    profession: "Marine Biologist",
    location_city: "Melbourne, VIC, Australia",
    address: "42 Flinders Lane, Melbourne VIC 3000, Australia",
    location_lat: -37.8136,
    location_lng: 144.9631,
    pets: ["Kelp"],
    social_links: {
      instagram: "oliver.sea",
      linkedin: "oliver-montague-marine",
    },
    about_me:
      "Marine biologist researching reef restoration and filming underwater ecosystems on weekends. I am the cousin most likely to answer from a boat.",
    country_code: "AUS",
    gallery_photos: gallery("ollie-reef", "ollie-dive"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "cousin-002",
    first_name: "Sophie",
    last_name: "Montague",
    display_name: null,
    gender: "female",
    avatar_url: portrait("women", 28),
    date_of_birth: "1994-04-11",
    place_of_birth: "Sydney, Australia",
    profession: "Climate Lawyer",
    location_city: "Singapore",
    address: "12 Marina View, Singapore 018961",
    location_lat: 1.3521,
    location_lng: 103.8198,
    pets: [],
    social_links: {
      linkedin: "sophie-montague-law",
    },
    about_me:
      "Climate finance attorney working across APAC infrastructure deals. I keep a color-coded spreadsheet for every trip and still never pack light.",
    country_code: "SGP",
    gallery_photos: gallery("sophie-office", "sophie-flight"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "grandparent-003",
    first_name: "Peter",
    last_name: "Parker",
    display_name: "Pete",
    gender: "male",
    avatar_url: portrait("men", 81),
    date_of_birth: "1938-05-06",
    date_of_death: "2019-01-21",
    place_of_birth: "Inverness, United Kingdom",
    profession: "Historian",
    location_city: "Edinburgh, United Kingdom",
    address: "8 Heriot Row, Edinburgh EH3 6HT, United Kingdom",
    location_lat: 55.9533,
    location_lng: -3.1883,
    pets: [],
    social_links: {},
    about_me:
      "Historian, collector of railway ephemera, and the reason every family anecdote comes with dates and citations.",
    country_code: "GBR",
    gallery_photos: gallery("peter-library", "peter-archive"),
    role: "MEMBER",
    is_alive: false,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "grandparent-004",
    first_name: "Rosemary",
    last_name: "Parker",
    display_name: "Rosie",
    gender: "female",
    avatar_url: portrait("women", 81),
    date_of_birth: "1940-12-17",
    place_of_birth: "Glasgow, United Kingdom",
    profession: "Headmistress (Retired)",
    location_city: "Edinburgh, United Kingdom",
    address: "8 Heriot Row, Edinburgh EH3 6HT, United Kingdom",
    location_lat: 55.9533,
    location_lng: -3.1883,
    pets: ["Bramble"],
    social_links: {},
    about_me:
      "Retired headmistress who can still silence a room with one look. I run the annual family raffle and never forget who owes me a postcard.",
    country_code: "GBR",
    gallery_photos: gallery("rosemary-tea", "rosemary-bramble"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "aunt-001",
    first_name: "Beatrice",
    last_name: "Walker",
    display_name: "Bea",
    gender: "female",
    avatar_url: portrait("women", 35),
    date_of_birth: "1968-10-03",
    place_of_birth: "Edinburgh, United Kingdom",
    profession: "Documentary Producer",
    location_city: "Toronto, ON, Canada",
    secondary_location_city: "Edinburgh, United Kingdom",
    address: "25 The Esplanade, Toronto, ON M5E 1W7, Canada",
    location_lat: 43.6532,
    location_lng: -79.3832,
    pets: ["Fern"],
    social_links: {
      instagram: "bea.docs",
      facebook: "beatrice.walker",
    },
    about_me:
      "Documentary producer focused on migration and urban history. I moved to Toronto twenty years ago and now host the North American branch of every family holiday.",
    country_code: "CAN",
    gallery_photos: gallery("bea-set", "bea-toronto"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
  {
    id: "cousin-003",
    first_name: "Nina",
    last_name: "Walker",
    display_name: null,
    gender: "female",
    avatar_url: portrait("women", 24),
    date_of_birth: "1998-08-29",
    place_of_birth: "Toronto, Canada",
    profession: "Public Health Analyst",
    location_city: "Toronto, ON, Canada",
    address: "25 The Esplanade, Toronto, ON M5E 1W7, Canada",
    location_lat: 43.6532,
    location_lng: -79.3832,
    pets: [],
    social_links: {
      linkedin: "nina-walker-ph",
    },
    about_me:
      "Public health analyst focused on maternal care access. I am the cousin who brings spreadsheets to family reunions and somehow gets thanked for it.",
    country_code: "CAN",
    gallery_photos: gallery("nina-cycling", "nina-cafe"),
    role: "MEMBER",
    is_alive: true,
    created_at: CREATED_AT,
    updated_at: CREATED_AT,
  },
];

// ── Relationships ───────────────────────────────
export const MOCK_RELATIONSHIPS: Relationship[] = [
  { id: "r1", user_id: "grandparent-001", relative_id: "parent-001", type: "parent", created_at: CREATED_AT },
  { id: "r2", user_id: "grandparent-002", relative_id: "parent-001", type: "parent", created_at: CREATED_AT },
  { id: "r3", user_id: "grandparent-001", relative_id: "uncle-001", type: "parent", created_at: CREATED_AT },
  { id: "r4", user_id: "grandparent-002", relative_id: "uncle-001", type: "parent", created_at: CREATED_AT },
  { id: "r5", user_id: "grandparent-003", relative_id: "parent-002", type: "parent", created_at: CREATED_AT },
  { id: "r6", user_id: "grandparent-004", relative_id: "parent-002", type: "parent", created_at: CREATED_AT },
  { id: "r7", user_id: "grandparent-003", relative_id: "aunt-001", type: "parent", created_at: CREATED_AT },
  { id: "r8", user_id: "grandparent-004", relative_id: "aunt-001", type: "parent", created_at: CREATED_AT },
  { id: "r9", user_id: "parent-001", relative_id: "viewer-001", type: "parent", created_at: CREATED_AT },
  { id: "r10", user_id: "parent-002", relative_id: "viewer-001", type: "parent", created_at: CREATED_AT },
  { id: "r11", user_id: "parent-001", relative_id: "sibling-001", type: "parent", created_at: CREATED_AT },
  { id: "r12", user_id: "parent-002", relative_id: "sibling-001", type: "parent", created_at: CREATED_AT },
  { id: "r12b", user_id: "viewer-001", relative_id: "sibling-001", type: "sibling", created_at: CREATED_AT },
  { id: "r13", user_id: "viewer-001", relative_id: "child-001", type: "parent", created_at: CREATED_AT },
  { id: "r14", user_id: "spouse-001", relative_id: "child-001", type: "parent", created_at: CREATED_AT },
  { id: "r15", user_id: "viewer-001", relative_id: "child-002", type: "parent", created_at: CREATED_AT },
  { id: "r16", user_id: "spouse-001", relative_id: "child-002", type: "parent", created_at: CREATED_AT },
  { id: "r17", user_id: "uncle-001", relative_id: "cousin-001", type: "parent", created_at: CREATED_AT },
  { id: "r18", user_id: "spouse-003", relative_id: "cousin-001", type: "parent", created_at: CREATED_AT },
  { id: "r19", user_id: "uncle-001", relative_id: "cousin-002", type: "parent", created_at: CREATED_AT },
  { id: "r20", user_id: "spouse-003", relative_id: "cousin-002", type: "parent", created_at: CREATED_AT },
  { id: "r21", user_id: "aunt-001", relative_id: "cousin-003", type: "parent", created_at: CREATED_AT },
  { id: "r22", user_id: "grandparent-001", relative_id: "grandparent-002", type: "spouse", marriage_date: "1957-06-15", created_at: CREATED_AT },
  { id: "r23", user_id: "grandparent-003", relative_id: "grandparent-004", type: "spouse", marriage_date: "1961-04-22", created_at: CREATED_AT },
  { id: "r24", user_id: "parent-001", relative_id: "parent-002", type: "spouse", marriage_date: "1988-09-10", created_at: CREATED_AT },
  { id: "r25", user_id: "viewer-001", relative_id: "spouse-001", type: "spouse", marriage_date: "2018-05-26", created_at: CREATED_AT },
  { id: "r27", user_id: "uncle-001", relative_id: "spouse-003", type: "spouse", marriage_date: "1987-11-14", created_at: CREATED_AT },
];

// ── User Conditions (who has what) ──────────────
export const MOCK_USER_CONDITIONS: UserCondition[] = [
  { id: "uc-1", user_id: "grandparent-001", condition_id: "cond-003", severity: "moderate", age_of_onset: 62, notes: "Managed with eye drops and regular monitoring.", diagnosed_at: "1994-05-01", created_at: CREATED_AT },
  { id: "uc-2", user_id: "grandparent-001", condition_id: "cond-002", severity: "mild", age_of_onset: 55, notes: null, diagnosed_at: "1987-03-01", created_at: CREATED_AT },
  { id: "uc-3", user_id: "grandparent-002", condition_id: "cond-015", severity: "moderate", age_of_onset: 68, notes: "Symptoms are stable with medication and aquatic exercise.", diagnosed_at: "2003-09-01", created_at: CREATED_AT },
  { id: "uc-4", user_id: "grandparent-003", condition_id: "cond-041", severity: "moderate", age_of_onset: 70, notes: "History of coronary artery disease late in life.", diagnosed_at: "2008-02-01", created_at: CREATED_AT },
  { id: "uc-5", user_id: "grandparent-004", condition_id: "cond-047", severity: "mild", age_of_onset: 58, notes: null, diagnosed_at: "1998-06-01", created_at: CREATED_AT },
  { id: "uc-6", user_id: "parent-001", condition_id: "cond-024", severity: "moderate", age_of_onset: 44, notes: "Strong family history; controlled with statin therapy.", diagnosed_at: "2004-11-01", created_at: CREATED_AT },
  { id: "uc-7", user_id: "parent-001", condition_id: "cond-002", severity: "mild", age_of_onset: 48, notes: null, diagnosed_at: "2008-11-01", created_at: CREATED_AT },
  { id: "uc-8", user_id: "parent-002", condition_id: "cond-020", severity: "moderate", age_of_onset: 35, notes: "Well controlled with therapy and medication.", diagnosed_at: "1998-02-01", created_at: CREATED_AT },
  { id: "uc-9", user_id: "parent-002", condition_id: "cond-014", severity: "mild", age_of_onset: 29, notes: "Gluten-free diet.", diagnosed_at: "1992-04-01", created_at: CREATED_AT },
  { id: "uc-10", user_id: "viewer-001", condition_id: "cond-004", severity: "mild", age_of_onset: 12, notes: "Exercise-induced; carries an inhaler.", diagnosed_at: "2004-09-01", created_at: CREATED_AT },
  { id: "uc-11", user_id: "spouse-001", condition_id: "cond-049", severity: "mild", age_of_onset: 9, notes: "Seasonal flares.", diagnosed_at: "2002-03-01", created_at: CREATED_AT },
  { id: "uc-12", user_id: "uncle-001", condition_id: "cond-001", severity: "moderate", age_of_onset: 52, notes: "Managed with diet and medication.", diagnosed_at: "2010-06-01", created_at: CREATED_AT },
  { id: "uc-13", user_id: "spouse-003", condition_id: "cond-046", severity: "mild", age_of_onset: 41, notes: null, diagnosed_at: "2002-08-01", created_at: CREATED_AT },
  { id: "uc-14", user_id: "cousin-001", condition_id: "cond-049", severity: "mild", age_of_onset: 7, notes: "Sensitive to cold-water diving conditions.", diagnosed_at: "1997-05-01", created_at: CREATED_AT },
  { id: "uc-15", user_id: "cousin-003", condition_id: "cond-020", severity: "mild", age_of_onset: 24, notes: "Managed with counseling.", diagnosed_at: "2022-01-01", created_at: CREATED_AT },
];
