// ══════════════════════════════════════════════════════════
// Legacy – Mock Data for Development
// ══════════════════════════════════════════════════════════

import type { Profile, Relationship, UserCondition } from "./types";
export { ALL_CONDITIONS as MOCK_CONDITIONS } from "./conditions-data";

// ── Family Members ──────────────────────────────
export const MOCK_PROFILES: Profile[] = [
  {
    id: "viewer-001",
    first_name: "Alexander",
    last_name: "Montague",
    display_name: "Alex",
    gender: "male",
    avatar_url: null,
    date_of_birth: "1992-03-15",
    place_of_birth: "London, United Kingdom",
    profession: "Architect",
    location_city: "New York, NY, USA",
    location_lat: 40.7128,
    location_lng: -74.006,
    pets: ["Luna"],
    social_links: { instagram: "alex.montague", linkedin: "alexandermontague" },
    about_me: "Third-generation architect with a passion for sustainable design. Currently leading urban renewal projects in Manhattan. Proud Montague — family is everything.",
    country_code: "USA",
    role: "ADMIN",
    is_alive: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "parent-001",
    first_name: "Edward",
    last_name: "Montague",
    display_name: "Ed",
    gender: "male",
    avatar_url: null,
    date_of_birth: "1960-07-22",
    place_of_birth: "Manchester, United Kingdom",
    profession: "Surgeon",
    location_city: "London, United Kingdom",
    location_lat: 51.5074,
    location_lng: -0.1278,
    pets: [],
    social_links: { linkedin: "dredwardmontague" },
    about_me: "Consultant cardiothoracic surgeon at St. Thomas' Hospital. Father of two. Still believe in the healing power of a Sunday roast.",
    country_code: "GBR",
    role: "MEMBER",
    is_alive: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "parent-002",
    first_name: "Catherine",
    last_name: "Montague",
    display_name: "Cate",
    gender: "female",
    avatar_url: null,
    date_of_birth: "1963-11-08",
    place_of_birth: "Edinburgh, United Kingdom",
    profession: "Professor of Literature",
    location_city: "London, United Kingdom",
    location_lat: 51.5074,
    location_lng: -0.1278,
    pets: ["Milo"],
    social_links: { facebook: "catherine.montague" },
    about_me: "Professor of Romantic Literature at King's College London. Published author. Avid gardener and terrible cook.",
    country_code: "GBR",
    role: "MEMBER",
    is_alive: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "sibling-001",
    first_name: "Isabella",
    last_name: "Montague",
    display_name: "Izzy",
    gender: "female",
    avatar_url: null,
    date_of_birth: "1995-06-12",
    place_of_birth: "London, United Kingdom",
    profession: "Journalist",
    location_city: "Paris, France",
    location_lat: 48.8566,
    location_lng: 2.3522,
    pets: ["Nori", "Peach"],
    social_links: { instagram: "isabellamontague", linkedin: "isabella-montague" },
    about_me: "Foreign correspondent for The Guardian, based in Paris. Fluent in French and Italian. Probably at a café right now.",
    country_code: "FRA",
    role: "MEMBER",
    is_alive: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "grandparent-001",
    first_name: "William",
    last_name: "Montague",
    display_name: "Will",
    gender: "male",
    avatar_url: null,
    date_of_birth: "1932-02-14",
    place_of_birth: "Bath, United Kingdom",
    profession: "Barrister (Retired)",
    location_city: "Bath, United Kingdom",
    location_lat: 51.3811,
    location_lng: -2.359,
    pets: [],
    social_links: {},
    about_me: "Retired Queen's Counsel. Served on the Royal Commission for Criminal Justice. A life well lived.",
    country_code: "GBR",
    role: "MEMBER",
    is_alive: false,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "grandparent-002",
    first_name: "Eleanor",
    last_name: "Montague",
    display_name: "Ellie",
    gender: "female",
    avatar_url: null,
    date_of_birth: "1935-09-30",
    place_of_birth: "Oxford, United Kingdom",
    profession: "Concert Pianist",
    location_city: "Bath, United Kingdom",
    location_lat: 51.3811,
    location_lng: -2.359,
    pets: ["Poppy"],
    social_links: {},
    about_me: "Retired concert pianist. Performed with the London Philharmonic. Now teaching grandchildren to love Chopin.",
    country_code: "GBR",
    role: "MEMBER",
    is_alive: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "uncle-001",
    first_name: "James",
    last_name: "Montague",
    display_name: "Jim",
    gender: "male",
    avatar_url: null,
    date_of_birth: "1958-04-18",
    place_of_birth: "Manchester, United Kingdom",
    profession: "Civil Engineer",
    location_city: "Sydney, NSW, Australia",
    location_lat: -33.8688,
    location_lng: 151.2093,
    pets: ["Ripley"],
    social_links: { linkedin: "james-montague-eng" },
    about_me: "Chief engineer at AECOM Sydney. Emigrated in '92. Love surfing, harbour views, and calling my brother at unreasonable hours.",
    country_code: "AUS",
    role: "MEMBER",
    is_alive: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cousin-001",
    first_name: "Oliver",
    last_name: "Montague",
    display_name: "Ollie",
    gender: "male",
    avatar_url: null,
    date_of_birth: "1990-12-01",
    place_of_birth: "Sydney, Australia",
    profession: "Marine Biologist",
    location_city: "Melbourne, VIC, Australia",
    location_lat: -37.8136,
    location_lng: 144.9631,
    pets: ["Kelp"],
    social_links: { instagram: "oliver.sea" },
    about_me: "Marine biologist studying coral reef recovery on the Great Barrier Reef. Part-time underwater photographer.",
    country_code: "AUS",
    role: "MEMBER",
    is_alive: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

// ── Relationships ───────────────────────────────
export const MOCK_RELATIONSHIPS: Relationship[] = [
  { id: "r1", user_id: "parent-001", relative_id: "viewer-001", type: "parent", created_at: "2024-01-01T00:00:00Z" },
  { id: "r2", user_id: "parent-002", relative_id: "viewer-001", type: "parent", created_at: "2024-01-01T00:00:00Z" },
  { id: "r3", user_id: "parent-001", relative_id: "sibling-001", type: "parent", created_at: "2024-01-01T00:00:00Z" },
  { id: "r4", user_id: "parent-002", relative_id: "sibling-001", type: "parent", created_at: "2024-01-01T00:00:00Z" },
  { id: "r5", user_id: "viewer-001", relative_id: "sibling-001", type: "sibling", created_at: "2024-01-01T00:00:00Z" },
  { id: "r6", user_id: "grandparent-001", relative_id: "parent-001", type: "parent", created_at: "2024-01-01T00:00:00Z" },
  { id: "r7", user_id: "grandparent-002", relative_id: "parent-001", type: "parent", created_at: "2024-01-01T00:00:00Z" },
  { id: "r8", user_id: "grandparent-001", relative_id: "uncle-001", type: "parent", created_at: "2024-01-01T00:00:00Z" },
  { id: "r9", user_id: "grandparent-002", relative_id: "uncle-001", type: "parent", created_at: "2024-01-01T00:00:00Z" },
  { id: "r10", user_id: "parent-001", relative_id: "uncle-001", type: "sibling", created_at: "2024-01-01T00:00:00Z" },
  { id: "r11", user_id: "uncle-001", relative_id: "cousin-001", type: "parent", created_at: "2024-01-01T00:00:00Z" },
  { id: "r12", user_id: "parent-001", relative_id: "parent-002", type: "spouse", created_at: "2024-01-01T00:00:00Z" },
  { id: "r13", user_id: "grandparent-001", relative_id: "grandparent-002", type: "spouse", created_at: "2024-01-01T00:00:00Z" },
];

// ── User Conditions (who has what) ──────────────
export const MOCK_USER_CONDITIONS: UserCondition[] = [
  { id: "uc-1", user_id: "grandparent-001", condition_id: "cond-003", severity: "moderate", age_of_onset: 62, notes: null, diagnosed_at: "1994-05-01", created_at: "2024-01-01T00:00:00Z" },
  { id: "uc-2", user_id: "grandparent-001", condition_id: "cond-002", severity: "mild", age_of_onset: 55, notes: null, diagnosed_at: "1987-03-01", created_at: "2024-01-01T00:00:00Z" },
  { id: "uc-3", user_id: "grandparent-002", condition_id: "cond-015", severity: "moderate", age_of_onset: 68, notes: "Managed with medication", diagnosed_at: "2003-09-01", created_at: "2024-01-01T00:00:00Z" },
  { id: "uc-4", user_id: "parent-001", condition_id: "cond-002", severity: "mild", age_of_onset: 48, notes: null, diagnosed_at: "2008-11-01", created_at: "2024-01-01T00:00:00Z" },
  { id: "uc-5", user_id: "parent-001", condition_id: "cond-003", severity: "mild", age_of_onset: 58, notes: "Early stage, monitoring", diagnosed_at: "2018-07-01", created_at: "2024-01-01T00:00:00Z" },
  { id: "uc-6", user_id: "parent-002", condition_id: "cond-020", severity: "moderate", age_of_onset: 35, notes: null, diagnosed_at: "1998-02-01", created_at: "2024-01-01T00:00:00Z" },
  { id: "uc-7", user_id: "uncle-001", condition_id: "cond-001", severity: "moderate", age_of_onset: 52, notes: null, diagnosed_at: "2010-06-01", created_at: "2024-01-01T00:00:00Z" },
  { id: "uc-8", user_id: "viewer-001", condition_id: "cond-004", severity: "mild", age_of_onset: 12, notes: "Childhood onset, well managed", diagnosed_at: "2004-09-01", created_at: "2024-01-01T00:00:00Z" },
];
